---
title: "Customer segmentation"
output: html_document
date: "2022-08-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

##load necessary libraries

library(tidyverse)
library(readxl)
library(here)
library(readr)
```

```{r}
##import data

transactions <- read_csv("cleancsv.csv")


transactions
```

```{r}
glimpse(transactions)
```

```{r}
##statistical summary
library(skimr)
skim(transactions)

```



```{r}
 
```
```{r}
#impute customer id with numbers

transactionsdf <- transactions %>% 
    group_by(customer_id) %>% 
    mutate(ID = cur_group_id()) %>% 
    arrange(ID) %>% 
    ungroup()

transactionsdf

```
```{r}
#data exploration

transactionsdf %>% 
    select(ID,income,value.amount,event,offer_type) %>% 
    distinct(ID,income,value.amount,event,offer_type)
```

```{r}

# total average spend per customer

transactionsspend <- transactionsdf %>% 
    select(ID,value.amount,income,event) %>% 
    filter(event == "transaction") %>% 
    group_by(ID) %>% 
    summarise(averagespent = mean(value.amount,na.rm = TRUE),
              averageincome = mean(income, na.rm = TRUE))  

transactionsspend
```
```{r}
transactionsspend %>% 
    summary()


```
```{r}
#Identify outliers
transactionsspend %>% 
    filter(averagespent > 200)
```

```{r}
#distribution of averagespent

library(tidyverse)

transactionsspend %>% 
    filter(averagespent < 200) %>% 
    ggplot(aes(x= averagespent)) + geom_boxplot(fill = '#006EA1', color = 'black')
```
```{r}
##Distribution of average income

transactionsspend %>% 
    ggplot(aes(x= averageincome)) + geom_histogram()
```

```{r}
##relationship between income and averagespend

transactionsspend %>% 
    ggplot(aes(x= averageincome,
               y = averagespent)) + geom_point()

```


```{r}
##Binning the data by creating ranks using the average spend

transactionsbin <- transactionsspend %>% 
    mutate(spendingscore = ntile(transactionsspend$averagespent,10))

transactionsbin
```

```{r}
transactionsbin %>% 
    filter(averagespent > 200)
```
```{r}
##K means clustering

```

